### ISSUE TITLE
Subdir and submodules request

### ISSUE THREAD

**Issue by italic-r** [BlenderAid/Asset-Flinger#1]
Hey flingers. @meta-androcto and I maintain a repo of a collection of addons (https://github.com/meta-androcto/blenderpython) and we have started moving addons with git repos into submodules. This way, any updates maintainers push to their repo, our repo will automatically pull when the users git pull. 

I noticed with asset-flinger that the addon is contained in a subdirectory within the repo (/Asset-Flinger/add_mesh_asset_flinger/*) which means if added as a submodule it won't register with blender. If it doesn't ruin anything, I'd like to request the addon be moved up a level into its root directory. That would make it easier for us and others to maintain and nobody has to worry about copy/pasting or symlinks. 

Thanks for consideration and happy blending!

**Comment by manujarvinen** [comment]
Ah, sorry for the late answer.

I need look into this, thanks for the suggestion

mj

---

manujarvinen.com http://www.manujarvinen.com | @manujarvinen
https://twitter.com/manujarvinen

**Comment by italic-r** [comment]
Hey Manu. Meta and I have decided to ditch the submodules because of some funky private key business with github. We don't necessarily need your repo to change to fit ours, so I'll leave that decision up to you. I'm marking as solved for that reason. Thanks for looking into it, though. It just didn't work out for meta for some reason.

**Comment by manujarvinen** [comment]
Thanks for the info :)

I'm still new at GitHub - but trying my best to provide what's needed
