### ISSUE TITLE
2.77 updates

### ISSUE THREAD

**Issue by italic-r** [BlenderAid/Asset-Flinger#5]
Hi Manu. Flinger works just fine in 2.76b, but with recent updates for 2.77, it screws with font rendering after activation. This only occurs after invoking the operation in the add mesh menu. 

If you plan to keep maintaining this addon, that'd be great. 

![asset_flinger](https://cloud.githubusercontent.com/assets/3143630/13200658/e761b37e-d806-11e5-88be-4927beb801f2.jpg)

**Comment by manujarvinen** [comment]
oh man :/ Thanks for notifying - I won't probably have skills to fix that.
And the other developers have other interestests than this little add-on.

Asset Flinger starts to be quite old anyway, here is a great alternative
with active support:
http://www.pitiwazou.com/asset-management-documentation_us/

mj

---

manujarvinen.com http://www.manujarvinen.com | @manujarvinen
https://twitter.com/manujarvinen

**Comment by italic-r** [comment]
We'll take it out of extern for now, then. I'm sure this git repo isn't going anywhere, so if you decide to pick it up again, we'll bring it back.

**Comment by manujarvinen** [comment]
Thanks. And sorry for the lack of development :/ I wish there was somebody
active who would be able and would like to continue developing it

---

manujarvinen.com http://www.manujarvinen.com | @manujarvinen
https://twitter.com/manujarvinen

**Comment by manujarvinen** [comment]
Oh, and thank you for the notes for my multi-boot-linux-article! :D I've
actually tweaked it to almost a publish-ready condition

---

manujarvinen.com http://www.manujarvinen.com | @manujarvinen
https://twitter.com/manujarvinen

**Comment by italic-r** [comment]
I'll give it a read when it's published for good.

**Comment by manujarvinen** [comment]
I had this same font problem, but just today I noticed when I downloaded
the latest 2.77 from builder that Asset Flinger was working again

Also Julian 'Severin' Eisel helped me to fix another issue that came with
2.77, I updated it to the GitHub-page and here:
http://files.manujarvinen.com/Asset_Flinger/Asset_Flinger_Add-on_v0.2.zip

Feel free to try if it works again :)

mj

---

manujarvinen.com http://www.manujarvinen.com | @manujarvinen
https://twitter.com/manujarvinen

**Comment by italic-r** [comment]
Yes, that seems to have done it. Thanks! I'll add it back to our repo with meta's approval.
