### ISSUE TITLE
if 3d view editor too small, it's not good to use [Suggestion]

### ISSUE THREAD

**Issue by Leroy-X** [BlenderAid/Asset-Flinger#6]
![01](https://cloud.githubusercontent.com/assets/13515498/13592471/404ca916-e52d-11e5-946c-45483315a03d.PNG)

Hello, if the 3d view too small, the Asset-Finger can't display completely, and I can't drag it down, so hope can add some function, like dray LMB or roll MMB.

BTW, it's only support .obj now, very hope it's can support .blend, and I can store blender information in the asset, like modifies, curve, even animation, like Append(Shift+F1), but more easy and human. Others, one time only support import one object now, hope can select multi object by one time.

Verrrrrrrrry thanks for your addons, it's so nice, just want to say thanks. sorry for my bad English : )

**Comment by manujarvinen** [comment]
Thanks for the comment :) I'm aware of the limitations, and since I'm not a developer, there's not much I can do. This is only a simple add-on.

For more hardcore users I typically recommend this asset management add-on: http://www.pitiwazou.com/asset-management/

**Comment by Leroy-X** [comment]
Yeah, the asset management is very strong, I like it too, thanks again :P
